import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { DataEntryData, getDocumentContent } from './document-types';

const NAVY = rgb(13 / 255, 31 / 255, 41 / 255);
const BLUE = rgb(42 / 255, 115 / 255, 228 / 255);
const GRAY = rgb(100 / 255, 100 / 255, 100 / 255);
const BLACK = rgb(0, 0, 0);

export async function generatePDF(docType: string, data: DataEntryData): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesRomanBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const { title, body } = getDocumentContent(docType, data);
  const margin = 60;
  const pageWidth = 595;
  const pageHeight = 842; // A4
  const contentWidth = pageWidth - margin * 2;
  const lineHeight = 16;
  const headerHeight = 80;

  let currentPage = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPos = pageHeight - margin;

  // Draw header
  function drawHeader(page: any, y: number): number {
    // Navy bar at top
    page.drawRectangle({
      x: 0, y: pageHeight - 4, width: pageWidth, height: 4, color: NAVY,
    });
    // Blue accent line
    page.drawRectangle({
      x: 0, y: pageHeight - 6, width: pageWidth, height: 2, color: BLUE,
    });

    // Firm name
    page.drawText(data.firmName || 'SBC & Co.', {
      x: margin, y: y - 10, size: 14, font: helveticaBold, color: NAVY,
    });
    page.drawText('Chartered Accountants', {
      x: margin, y: y - 26, size: 9, font: helvetica, color: GRAY,
    });

    // Separator line
    page.drawLine({
      start: { x: margin, y: y - 35 },
      end: { x: pageWidth - margin, y: y - 35 },
      thickness: 0.5, color: BLUE,
    });

    return y - 55;
  }

  // Draw footer
  function drawFooter(page: any) {
    page.drawLine({
      start: { x: margin, y: 50 },
      end: { x: pageWidth - margin, y: 50 },
      thickness: 0.5, color: GRAY,
    });
    page.drawText('Generated by KudosFlow — Audit Document Automation Platform', {
      x: margin, y: 36, size: 7, font: helvetica, color: GRAY,
    });
    page.drawText(`${data.firmName || 'SBC & Co.'} | Confidential`, {
      x: pageWidth - margin - 140, y: 36, size: 7, font: helvetica, color: GRAY,
    });
  }

  yPos = drawHeader(currentPage, yPos);

  // Document title
  currentPage.drawText(title, {
    x: margin, y: yPos, size: 13, font: timesRomanBold, color: NAVY,
  });
  yPos -= 8;

  // Title underline
  const titleWidth = timesRomanBold.widthOfTextAtSize(title, 13);
  currentPage.drawLine({
    start: { x: margin, y: yPos },
    end: { x: margin + titleWidth, y: yPos },
    thickness: 1, color: BLUE,
  });
  yPos -= 24;

  // Body text
  for (const line of body) {
    if (yPos < 70) {
      drawFooter(currentPage);
      currentPage = pdfDoc.addPage([pageWidth, pageHeight]);
      yPos = pageHeight - margin;
      yPos = drawHeader(currentPage, yPos);
    }

    if (line === '') {
      yPos -= lineHeight * 0.6;
      continue;
    }

    // Word wrap
    const words = line.split(' ');
    let currentLine = '';
    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const testWidth = timesRoman.widthOfTextAtSize(testLine, 11);
      if (testWidth > contentWidth && currentLine) {
        currentPage.drawText(currentLine, {
          x: margin, y: yPos, size: 11, font: timesRoman, color: BLACK,
        });
        yPos -= lineHeight;
        if (yPos < 70) {
          drawFooter(currentPage);
          currentPage = pdfDoc.addPage([pageWidth, pageHeight]);
          yPos = pageHeight - margin;
          yPos = drawHeader(currentPage, yPos);
        }
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }
    if (currentLine) {
      const isSignLine = currentLine.startsWith('______');
      const isNumbered = /^\d+\./.test(currentLine);
      currentPage.drawText(currentLine, {
        x: isNumbered ? margin + 10 : margin,
        y: yPos,
        size: 11,
        font: isSignLine ? timesRoman : timesRoman,
        color: BLACK,
      });
      yPos -= lineHeight;
    }
  }

  drawFooter(currentPage);

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}
